### ISSUE TITLE
Image size

### ISSUE THREAD

**Issue by jboy1234** [TheExeLab/Spigotly#1]
The image on the frount page does not scale on large screens.

Image:
https://gyazo.com/09cbc094e6c922960ca40ea20cae1748

**Comment by jboy1234** [comment]
My mistake my zoom was set wrong.

**Comment by jboy1234** [comment]
Disregaurd that last close, theres multiple images which the one in the screenshot does not dynamicaly  size

**Comment by TheExeLab** [comment]
Fixing it right now!
