### ISSUE TITLE
No Footer

### ISSUE THREAD

**Issue by jboy1234** [TheExeLab/Spigotly#2]
Theres no footer on the web app. You should add one such as:

<div id="footer">
Copyright YourName, The year ( If you have php use <?php echo date("Y"); ?> for the year )
</div>

Then add some nice style for the footer with

#footer {
    background-color:gray;
    color:white;
    clear:both;
    text-align:center;
    padding:10px; 
}

**Comment by TheExeLab** [comment]
Adding footer! Thanks
